import { Technician } from './src/app/features/job-order/models/api-response.interface';

export const dummyTechnician: Technician[] = [
  {
    id: '1',
    name: 'John Doe',
    skills: ['Skill 1', 'Skill 2'],
    location: 'Location 1',
    availability: 'Available',
  },
  {
    id: '2',
    name: 'Jane Doe',
    skills: ['Skill 3', 'Skill 4'],
    location: 'Location 2',
    availability: 'Not Available',
  },
  {
    id: '3',
    name: 'John Smith',
    skills: ['Skill 5', 'Skill 6'],
    location: 'Location 3',
    availability: 'Available',
  },
  {
    id: '4',
    name: 'Jane Smith',
    skills: ['Skill 7', 'Skill 8'],
    location: 'Location 4',
    availability: 'Not Available',
  },
  {
    id: '5',
    name: 'John Doe',
    skills: ['Skill 9', 'Skill 10'],
    location: 'Location 5',
    availability: 'Available',
  },
  {
    id: '6',
    name: 'Jane Doe',
    skills: ['Skill 11', 'Skill 12'],
    location: 'Location 6',
    availability: 'Not Available',
  },
  {
    id: 'tech1',
    name: 'John Doe',
    skills: ['Electrical'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech2',
    name: 'Jane Smith',
    skills: ['Plumbing'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech3',
    name: 'Michael Johnson',
    skills: ['Carpentry'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech4',
    name: 'Emily Davis',
    skills: ['HVAC'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech5',
    name: 'James Brown',
    skills: ['Painting'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech6',
    name: 'Patricia Taylor',
    skills: ['Welding'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech7',
    name: 'Robert Miller',
    skills: ['Electrical', 'Plumbing'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech8',
    name: 'Linda Wilson',
    skills: ['Carpentry'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech9',
    name: 'David Moore',
    skills: ['HVAC', 'Painting'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech10',
    name: 'Barbara Clark',
    skills: ['Welding'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech11',
    name: 'Richard Lewis',
    skills: ['Electrical'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech12',
    name: 'Susan Walker',
    skills: ['Plumbing'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech13',
    name: 'Joseph Hall',
    skills: ['Carpentry'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech14',
    name: 'Sarah Allen',
    skills: ['HVAC'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech15',
    name: 'Charles Young',
    skills: ['Painting'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech16',
    name: 'Karen Hernandez',
    skills: ['Welding'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech17',
    name: 'Daniel King',
    skills: ['Electrical', 'Plumbing'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech18',
    name: 'Nancy Wright',
    skills: ['Carpentry'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech19',
    name: 'Matthew Lopez',
    skills: ['HVAC', 'Painting'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech20',
    name: 'Betty Hill',
    skills: ['Welding'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech21',
    name: 'Anthony Scott',
    skills: ['Electrical'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech22',
    name: 'Sandra Green',
    skills: ['Plumbing'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech23',
    name: 'Mark Adams',
    skills: ['Carpentry'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech24',
    name: 'Donna Baker',
    skills: ['HVAC'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech25',
    name: 'Paul Gonzalez',
    skills: ['Painting'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech26',
    name: 'Carol Nelson',
    skills: ['Welding'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech27',
    name: 'Steven Carter',
    skills: ['Electrical', 'Plumbing'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech28',
    name: 'Ruth Mitchell',
    skills: ['Carpentry'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech29',
    name: 'Andrew Perez',
    skills: ['HVAC', 'Painting'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech30',
    name: 'Sharon Roberts',
    skills: ['Welding'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech31',
    name: 'Kenneth Turner',
    skills: ['Electrical'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech32',
    name: 'Dorothy Phillips',
    skills: ['Plumbing'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech33',
    name: 'Joshua Campbell',
    skills: ['Carpentry'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech34',
    name: 'Deborah Parker',
    skills: ['HVAC'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech35',
    name: 'Kevin Evans',
    skills: ['Painting'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech36',
    name: 'Jennifer Edwards',
    skills: ['Welding'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech37',
    name: 'Brian Collins',
    skills: ['Electrical', 'Plumbing'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech38',
    name: 'Maria Stewart',
    skills: ['Carpentry'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech39',
    name: 'George Sanchez',
    skills: ['HVAC', 'Painting'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech40',
    name: 'Laura Morris',
    skills: ['Welding'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech41',
    name: 'Edward Rogers',
    skills: ['Electrical'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech42',
    name: 'Melissa Reed',
    skills: ['Plumbing'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech43',
    name: 'Ronald Cook',
    skills: ['Carpentry'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech44',
    name: 'Ashley Morgan',
    skills: ['HVAC'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
  {
    id: 'tech45',
    name: 'Gary Bell',
    skills: ['Painting'],
    location: 'Chicago, IL',
    availability: 'Available',
  },
  {
    id: 'tech46',
    name: 'Kimberly Murphy',
    skills: ['Welding'],
    location: 'Houston, TX',
    availability: 'Not Available',
  },
  {
    id: 'tech47',
    name: 'Jeffrey Bailey',
    skills: ['Electrical', 'Plumbing'],
    location: 'Phoenix, AZ',
    availability: 'Available',
  },
  {
    id: 'tech48',
    name: 'Amy Rivera',
    skills: ['Carpentry'],
    location: 'Miami, FL',
    availability: 'Not Available',
  },
  {
    id: 'tech49',
    name: 'Scott Cooper',
    skills: ['HVAC', 'Painting'],
    location: 'New York, NY',
    availability: 'Available',
  },
  {
    id: 'tech50',
    name: 'Cynthia Richardson',
    skills: ['Welding'],
    location: 'Los Angeles, CA',
    availability: 'Not Available',
  },
];
